---
- name: apache docker
  hosts: docker
  become: yes
  tasks: 
  - name: instalando apache
    apt: 
      name: apache2
      state: present
  - name: verificando instalacao
    service:
      name: apache2
      state: started
      enabled: true
  - name: template com index.html
    template:
      src: /root/index.html
      dest: /var/www/html/index.html
      force: yes
  - name: instalando php
    apt:
      name: libapache2-mod-php
      state: present
  - name: restart apache
    service:
      name: apache2
      state: restarted
  - name: baixando compactado
    unarchive:
      src: https://hectorvido.dev/site.tar.gz
      dest: /var/www/html
      remote_src: yes
  - name: removendo arquivo
    file:
      path: /var/www/html/index.html
      state: absent


      #- name: copiando index.html
      #  copy:
      #    src: /root/index.html
      #    dest: /var/www/html/index.html
      #    force: yes 
...
