---
- name: apache docker
  hosts: docker
  become: yes
  tasks: 
  - name: instalando apache
    apt: 
      name: apache2
      state: present
  - name: verificando instalacao
    service:
      name: apache2
      state: started
      enabled: true 
...
